# Starter pipeline
- task: katalonTask@0
  inputs:
    version: '7.9.1'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="C:\Users\Group10\git\ProAcc_Update2.0NewUI\ProAcc_Update2.0NewUI.prj" -retry=0 -testSuitePath="Test Suites/ProAcc_Suite" -executionProfile="ProAcc" -browserType="Chrome (headless)"'
- task: katalonTask@0
  inputs:
    version: '7.9.1'
    executeArgs: 'katalonc -noSplash -runMode=console -projectPath="G:\Pro ACC\ProAccLatest-master\ProAcc.prj" -retry=0 -testSuitePath="Test Suites/Assesment_Suite" -executionProfile="default" -browserType="Chrome" -apiKey="c1e0aeec-093a-4991-8bd0-39a52de42523" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY -proxy.system.applyToDesiredCapabilities=true'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
